title: Site name here
url: http://site-url-here.com
# baseurl: /base-url-here
description: Description of site here

author: 
  name: Katy DeCorah
  email: katydecorah@gmail.com
  uri: http://katydecorah.com
  twitter: katydecorah

twitter: 
  username: katydecorah

logo: http://placehold.it/300
image: http://placehold.it/300

permalink: pretty

sass:
  style: :compressed

timezone: America/New_York

exclude:
- node_modules
- Gemfile
- README.md
- .sass-cache

gems:
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# CDN versions
jquery: 2.2.4
